In [ ]:
#Q.1 How do you create a Pandas DataFrame?
import pandas as pd
data= {
    'Name':['Alice','Bob','Claire'],
    'Age':[25,30,27],
    'Gender':['Female','Male','Female']
}
df=pd.DataFrame(data)
print(df)

     Name  Age  Gender
0   Alice   25  Female
1     Bob   30    Male
2  Claire   27  Female

In [ ]:
# Q.2 How do you read a CSV file into a Pandas DataFrame?
import pandas as pd
df=pd.read_csv('covid_toy.csv')
df.head(5)

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
# Q.3 How do you check for missing values in a DataFrame?
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
# Q.4 How do you drop rows with missing values?
df.dropna()

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[90 rows x 6 columns]

In [ ]:
#Q.5 How do you fill missing values with a specific value?
df.fillna(0)

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [ ]:
# Q.6 How do you filter rows based on a condition?
df[df['age']>20]

    age  gender  fever   cough     city has_covid
0    60    Male  103.0    Mild  Kolkata        No
1    27    Male  100.0    Mild    Delhi       Yes
2    42    Male  101.0    Mild    Delhi        No
3    31  Female   98.0    Mild  Kolkata        No
4    65  Female  101.0    Mild   Mumbai        No
..  ...     ...    ...     ...      ...       ...
91   38    Male    NaN    Mild    Delhi       Yes
92   82  Female  102.0  Strong  Kolkata        No
93   27    Male  100.0    Mild  Kolkata       Yes
94   79    Male    NaN  Strong  Kolkata       Yes
96   51  Female  101.0  Strong  Kolkata       Yes

[74 rows x 6 columns]

In [ ]:
# Q.7 How do you select a specific column in a DataFrame?
df['age']

0     60
1     27
2     42
3     31
4     65
      ..
95    12
96    51
97    20
98     5
99    10
Name: age, Length: 100, dtype: int64

In [ ]:
# Q.8 How do you rename columns in a DataFrame?
df.rename(columns={'has_covid':'has_Covid'})

    age  gender  fever   cough       city has_Covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [ ]:
# Q.9 How do you sort a DataFrame by a specific column?
df.sort_values(by= 'age')

    age  gender  fever   cough       city has_covid
98    5  Female   98.0  Strong     Mumbai        No
75    5    Male  102.0    Mild    Kolkata       Yes
88    5  Female  100.0    Mild    Kolkata        No
59    6  Female  104.0    Mild    Kolkata       Yes
77    8  Female  101.0    Mild    Kolkata        No
..  ...     ...    ...     ...        ...       ...
35   82  Female  102.0  Strong  Bangalore        No
72   83  Female  101.0    Mild    Kolkata        No
53   83    Male   98.0    Mild      Delhi       Yes
31   83    Male  103.0    Mild    Kolkata        No
5    84  Female    NaN    Mild  Bangalore       Yes

[100 rows x 6 columns]

In [ ]:
# Q.10 How do you group data and calculate aggregate statistics?
df.groupby('has_covid').sum()

,age,gender,fever,cough,city
has_covid,,,,,
No,2465,MaleMaleFemaleFemaleMaleFemaleFemaleFemaleFema...,5261.0,MildMildMildMildStrongStrongMildMildStrongMild...,KolkataDelhiKolkataMumbaiBangaloreBangaloreDel...
Yes,1957,MaleFemaleFemaleFemaleMaleMaleFemaleFemaleFema...,3815.0,MildMildStrongMildMildStrongMildMildStrongMild...,DelhiBangaloreMumbaiMumbaiBangaloreKolkataKolk...

In [ ]:
# Q.11 How do you reset the index of a DataFrame?
# df.reset_index()
df.reset_index(drop=True, inplace=True)

In [ ]:
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [ ]:
# Q.12 How do you merge two DataFrames?
import pandas as pd
df1=pd.DataFrame({'id':[12,34],'name':['asd','qwe']})
df2=pd.DataFrame({'id':[12,34,45],'name':['ram','shu','df']})
pd.merge(df1,df2,on='id')

   id name_x name_y
0  12    asd    ram
1  34    qwe    shu

In [ ]:
# Q.13 How do you concatenate two DataFrames?
pd.concat([df1,df2])

   id name
0  12  asd
1  34  qwe
0  12  ram
1  34  shu
2  45   df

In [ ]:
# Q.14 How do you pivot a DataFrame?
df.pivot(columns='has_covid',values='age')

has_covid    No   Yes
0          60.0   NaN
1           NaN  27.0
2          42.0   NaN
3          31.0   NaN
4          65.0   NaN
..          ...   ...
95         12.0   NaN
96          NaN  51.0
97         20.0   NaN
98          5.0   NaN
99          NaN  10.0

[100 rows x 2 columns]

In [ ]:
# Q.15 How do you melt a DataFrame?
df.melt(id_vars='has_covid',value_vars='age')

   has_covid variable  value
0         No      age     60
1        Yes      age     27
2         No      age     42
3         No      age     31
4         No      age     65
..       ...      ...    ...
95        No      age     12
96       Yes      age     51
97        No      age     20
98        No      age      5
99       Yes      age     10

[100 rows x 3 columns]