In [1]:
# Pandas ===> It is an open source library that is used for handle data manipulations.

# Data structure of pandas
# 1. series ===> It is one dimensional array. it contains only values not column name
# 2. Dataframe ==> It is muldimensional array. it contains values with column name

In [2]:
import pandas as pd

## Series

In [3]:
a= pd.Series([1,2,3,4,5])
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
type(a)

pandas.core.series.Series

## DataFrame

In [7]:
a={
    "Emp_id":[1,2,3,4,5,6,7],
    "name":['sam','shiv','ram','shyam','shiv','pallavi','sam'],
    "Department":['IT','sales','IT','sales','IT','sales','operations'],
    "Working_hours":[8,9,8,7,8,9,9]

}

In [8]:
type(a)

dict

In [9]:
df=pd.DataFrame(a)
df

   Emp_id     name  Department  Working_hours
0       1      sam          IT              8
1       2     shiv       sales              9
2       3      ram          IT              8
3       4    shyam       sales              7
4       5     shiv          IT              8
5       6  pallavi       sales              9
6       7      sam  operations              9

## import and export our dataframe

## export

In [16]:
df.to_csv("C:\\Users\\91937\\OneDrive\\Desktop\\aadi\\emp_info.csv",index=False)   ## index=False is for to remove indexing values

## import

In [14]:
df1=pd.read_csv("C:\\Users\\91937\\OneDrive\\Desktop\\aadi\\emp_info.csv")

In [15]:
df1

   Emp_id     name  Department  Working_hours
0       1      sam          IT              8
1       2     shiv       sales              9
2       3      ram          IT              8
3       4    shyam       sales              7
4       5     shiv          IT              8
5       6  pallavi       sales              9
6       7      sam  operations              9

In [17]:
df

   Emp_id     name  Department  Working_hours
0       1      sam          IT              8
1       2     shiv       sales              9
2       3      ram          IT              8
3       4    shyam       sales              7
4       5     shiv          IT              8
5       6  pallavi       sales              9
6       7      sam  operations              9

## head() and tail()

In [18]:
df.head()

   Emp_id   name Department  Working_hours
0       1    sam         IT              8
1       2   shiv      sales              9
2       3    ram         IT              8
3       4  shyam      sales              7
4       5   shiv         IT              8

In [19]:
df.head(2)

   Emp_id  name Department  Working_hours
0       1   sam         IT              8
1       2  shiv      sales              9

In [20]:
df.tail()

   Emp_id     name  Department  Working_hours
2       3      ram          IT              8
3       4    shyam       sales              7
4       5     shiv          IT              8
5       6  pallavi       sales              9
6       7      sam  operations              9

In [21]:
df.tail(2)

   Emp_id     name  Department  Working_hours
5       6  pallavi       sales              9
6       7      sam  operations              9

## check random index data

In [22]:
df.sample(3)

   Emp_id     name Department  Working_hours
1       2     shiv      sales              9
2       3      ram         IT              8
5       6  pallavi      sales              9

In [24]:
df.shape # check shape

(7, 4)

In [25]:
df.columns  ## check columns name

Index(['Emp_id', 'name', 'Department', 'Working_hours'], dtype='object')

## case 1
you have to update "ram'to 'ravan'

In [26]:
df['name'][2]='ravan'

C:\Users\91937\AppData\Local\Temp\ipykernel_14348\2383994329.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['name'][2]='ravan'
C:\Users\91937\AppData\Local\Temp\ipykernel_14348\2383994329.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['name'][2]='ravan'

In [27]:
df

   Emp_id     name  Department  Working_hours
0       1      sam          IT              8
1       2     shiv       sales              9
2       3    ravan          IT              8
3       4    shyam       sales              7
4       5     shiv          IT              8
5       6  pallavi       sales              9
6       7      sam  operations              9

In [31]:
df['Working_hours'][1]=10

C:\Users\91937\AppData\Local\Temp\ipykernel_14348\4155008706.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Working_hours'][1]=10
C:\Users\91937\AppData\Local\Temp\ipykernel_14348\4155008706.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Working_hours'][1]=10

In [32]:
df

   Emp_id     name  Department  Working_hours
0       1      sam          IT              8
1       2     shiv       sales             10
2       3    ravan          IT              8
3       4    shyam       sales              7
4       5     shiv          IT              8
5       6  pallavi       sales              9
6       7      sam  operations              9

## check totsl sub_categories frequency of a column

In [33]:
df['name'].value_counts()

name
sam        2
shiv       2
ravan      1
shyam      1
pallavi    1
Name: count, dtype: int64

In [34]:
df['Department'].value_counts()

Department
IT            3
sales         3
operations    1
Name: count, dtype: int64

In [35]:
## check null value

In [36]:
df.isnull().sum()

Emp_id           0
name             0
Department       0
Working_hours    0
dtype: int64

In [37]:
df['name'][3]=None
df['Department'][4]=None

C:\Users\91937\AppData\Local\Temp\ipykernel_14348\1281631395.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['name'][3]=None
C:\Users\91937\AppData\Local\Temp\ipykernel_14348\1281631395.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['name'][3]=None
C:\Users\91937\AppData\Local\Temp\ipykernel_14348\1281631395.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Department'][4]=None
C:\Users\91937\AppData\Local\Temp\ipykernel_14348\1281631395.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Department'][4]=None

In [38]:
df.isnull().sum()

Emp_id           0
name             1
Department       1
Working_hours    0
dtype: int64

## Task 2
dataframe==> student_information
columns===> student_id, course_name, course,duration, fees

data import and export
head(),tail(),sample()
create missing data , handle missing data
value_counts()